### ISSUE TITLE
Als speler wil ik de doelstelling van de game kunnen zien, zodat ik weet welke taken ik moet gaan uitvoeren in het spel.

### ISSUE THREAD

**Issue by QuintenvDriel** [AIDDEI/life-below-water#15]
## Acceptatiecriteria

- [x]  Het doel is vetgedrukt 
- [x]  Het doel staat op het introscherm van de dag onder het dagnummer (Dag # 5 ENTER tekst)

## Definition of Done 
De speler weet wat het doel van het spel is aan de hand van het introverhaaltje ( #12  )  en aan het begin van elke dag.

**Comment by Isissss** [comment]
PR #33
