### ISSUE TITLE
Als gebruiker wil ik een betekenisvolle keuze kunnen maken bij het veranderen van de parameters zodat ik weet dat mijn keuzes ertoe doen

### ISSUE THREAD

**Issue by Isissss** [AIDDEI/life-below-water#21]
## Acceptatiecriteria

- [ ] Na elke keuze wordt er een predict() uitgevoerd na het kiezen van nieuwe waardes
- [ ] De data wordt in de app geladen en er kan een pedict worden uitgevoerd 

## Definition of Done
Er kan op basis van een dataset een predict worden uigevoerd op de kwaliteit van het water met de gegeven parameters waar de speler in keuze in kan maken

**Comment by PimMiii** [comment]
- AI/Model niet langer van toepassing. (zou mogelijk nog via fetch naar een API kunnen)

- Parameter class is gemaakt.
